name: schedule
on:
  schedule:
    - cron: '30 15 * * *'
jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: node dist/cli.js algolia
      - run: node dist/cli.js push
